### ISSUE TITLE
salt-repo RPMs: `$releasever` varible may contain minor version on some RHEL-based OS

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-pack#310]
Hi @dmurphy18 

The documentation page at http://repo.saltstack.com/#rhel recommends to install the SaltStack repository and key like this:
```bash
sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el7.noarch.rpm 
```

That RPM (and others like `salt-repo-2016.11-1.el7.noarch.rpm`, etc) contains the `/etc/yum.repos.d/salt-latest.repo` file with the following contents:
```ini
[salt-latest]
name=SaltStack Latest Release Channel for RHEL/Centos $releasever
baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key
```

The issue is that the special variable `$releasever`, which honored by `yum`, sometimes may contain the version in form of `major.minor`, e.g. `7.3` or `6.9` on some variants of RHEL, such as Cloud Linux or Scientific Linux. This causes the HTTP 404 error when attempting to install Salt, because there is no such URL path, i.e. http://repo.saltstack.com/yum/redhat/7.3/ in the repo.

My suggestion is to set up static major release version in the `baseurl` in each package, like this:
```yaml
salt-repo-latest-1.el7.noarch.rpm: baseurl=https://repo.saltstack.com/yum/redhat/7/$basearch/latest
salt-repo-latest-1.el6.noarch.rpm: baseurl=https://repo.saltstack.com/yum/redhat/6/$basearch/latest
salt-repo-latest-1.el5.noarch.rpm: baseurl=https://repo.saltstack.com/yum/redhat/5/$basearch/latest
```
Apply the same approach to `salt-repo` RPM packages for releases `2016.11`, `2016.3` and so on.

I think that would be really great. Thanks.
