### ISSUE TITLE
Add python-systemd to Debian Jessie repository

### ISSUE THREAD

**Issue by kaaelhaa** [saltstack/salt-pack#657]
With the release of Salt 2019.2.0 our automated deployments of Salt with the `virt` runner has stopped working. 

We're deploying VMs based on the official Debian OpenStack images (as we then don't need to maintain these ourselves). These images does not include the Debian backports repository which is required for resolving the `python-systemd` dependency.

Please consider adding `python-systemd` to the Salt Debian repository, as our automated deployments currently are ... not so automated.

**Comment by dmurphy18** [comment]
@kaaelhaa The aim of the SaltStack repositories for both Redhat/Amazon/Debian/Ubuntu are to provide Salt for that platform and any dependencies which the OS platform does not supply at a sufficient version for Salt to function.  For example: Debian 8.0 did not supply python-systemd initially but now does since v8.5.  Python-tornado v4.2.1 was provided initially since versions shipped were insufficient versions for Salt to operate, but subsequently newer versions are now supplied by OS platforms.

It was found during testing, that some conflicts were occurring between the version of python-systemd built by SaltStack and that provided by the Debian OS and it was decided to stop continuing building and providing python-systemd and defer to the version provided by the OS platform, especially since the conflicts prevented installation.

Hope that this explains the reasons for removing it.

**Comment by myii** [comment]
For Docker, using `debian:jessie-backports` has worked for us (the reference link directly above).

**Comment by getSurreal** [comment]
For kitchen tests using vagrant you can inject backports into it.

```
platforms:
  - name: bento/debian-8.7
    lifecycle:
      post_create:
      - remote: echo 'deb http://deb.debian.org/debian jessie-backports main' | sudo tee -a /etc/apt/sources.list
      - remote: sudo apt-get update

```
